name: Python CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Allow one of the matrix builds to fail without failing others
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        
        
    # The job
    name: Python ${{ matrix.python-version }} / ${{ matrix.os }}
    
    # The steps in the job. Each step either RUNS code, or USES an action
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      - name: Run tests and linting
        run: |
          pip install pip --upgrade
          pip install black
          black pygam --check -l 120
